<?php

declare(strict_types=1);

namespace Sculpt\ApiDoc\Generators;

use Illuminate\Support\Facades\Route;
use Sculpt\ApiDoc\Extractors\DtoExtractor;

final class OpenApiGenerator
{
    private DtoExtractor $dtoExtractor;

    public function __construct()
    {
        $this->dtoExtractor = new DtoExtractor();
    }

    public function generate(): array
    {
        $spec = [
            'openapi' => '3.1.0',
            'info' => [
                'title'       => config('sculpt-apidoc.title', 'Sculpt API Documentation'),
                'description' => config('sculpt-apidoc.description', 'Powerful and clean API documentation generated by Sculpt'),
                'version'     => config('sculpt-apidoc.version', '1.0.0'),
            ],
            'servers' => [
                ['url' => config('app.url')],
            ],
            'paths' => $this->collectPaths(),
        ];

        return $spec;
    }

    private function collectPaths(): array
    {
        $paths = [];

        foreach (Route::getRoutes() as $route) {
            if (!str_starts_with($route->uri(), 'api/')) {
                continue;
            }

            $action = $route->getAction('controller');
            if (!$action || !class_exists($action)) {
                continue;
            }

            $controller = new \ReflectionClass($action);
            $method = $controller->getMethod('__invoke');

            $path = '/' . ltrim($route->uri(), '/');
            $httpMethod = strtolower($route->methods()[0]);

            $paths[$path][$httpMethod] = $this->dtoExtractor->extract($method, $route);
        }

        return $paths;
    }
}